[package]
name = "solana-config-program"
version = "1.8.14"
description = "Solana Config program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-config-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
log = "0.4.11"
rand_core = "0.6.2"
serde = "1.0.122"
serde_derive = "1.0.103"
solana-sdk = { git = "https://github.com/solindex/sdk.git", version = "=1.8.14" }

[dev-dependencies]
solana-logger = { git = "https://github.com/solindex/logger.git", version = "=1.8.14" }

[lib]
crate-type = ["lib"]
name = "solana_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
